apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  Corefile: |
    cluster.local {
      errors
      health {
        lameduck 5s
      }
      ready
      kubernetes cluster.local 169.169.0.0/16 {
        fallthrough in-addr.arpa ip6.arpa
      }
      prometheus: 9153
      forward . /etc/resolv.conf
      cache 30
      loop
      reload
      loadbalance
    }
    . {
      cache 30
      loadbalance
      forward . /etc/resolv.conf
    }